language: python
python:
 - 2.7
install:
 - pip install -r requerimientos.txt
before_script: 
 - autopep8 -ir *
script: 
 - cd ../pruebas_unitarias
 - python TestArea.py
 - coverage run TestArea.py
 - coverage html